### PR TITLE
Add CMakeLists.txt and support for MSVC

### PR DESCRIPTION
**Pull request by b-r-o-c-k**

### CODE REVIEW

**Comment by blueyed** [comment]
@b-r-o-c-k 
Thanks for this already.
Do you think we could/should have tests/CI using AppVeyor for/with this?

**Comment by blueyed** [comment]
Rebased, and added a job to build with CMake.

**Comment by blueyed** [comment]
Tested that it is really using the lib built with CMake in 6c6351c (https://travis-ci.com/neovim/unibilium/jobs/223220172).

**Comment by blueyed** [comment]
@b-r-o-c-k 
Is this good / ready from your side?

**Comment by b-r-o-c-k** [comment]
Yes, looks good!

**Pull request merged**
