### PR TITLE
Stop searching in further dirs on errors except ENOENT

### PR DESCRIPTION
**Pull request by blueyed**
Taking over https://github.com/mauke/unibilium/pull/41.

### CODE REVIEW

**Comment by justinmk** [comment]
- included the description from https://github.com/mauke/unibilium/pull/41 in the commit message
- included reference to https://github.com/mauke/unibilium/pull/41 in the commit message

**Comment by blueyed** [comment]
@justinmk 
I wanted to check how this behaves with regard to compatibility with ncurses, and also add tests..

**Comment by blueyed** [comment]
`infocmp` at least behaves differently:
```
% cp /usr/share/terminfo/s/screen t/fixtures/invalid/s/screen
% TERMINFO=$PWD/t/fixtures/invalid infocmp screen
#	Reconstructed via infocmp from file: …/Vcs/unibilium/t/fixtures/invalid/s/screen
…
% echo invalid > $PWD/t/fixtures/invalid/s/screen
% TERMINFO=$PWD/t/fixtures/invalid infocmp screen
#	Reconstructed via infocmp from file: /usr/share/terminfo/s/screen
…
```

**Comment by blueyed** [comment]
However this patch does not change the behavior with "TERMINFO".

Might be good then for now.

**Comment by pschyska** [comment]
This led to my vim silently failing on a TERMINFO_DIRS which was present, but not a directory; `~/.local/share/flatpak/exports` was a file, no idea how this happened ¯\\_(ツ)_/¯.
Neovim's `&term` fell back to `builtin_ansi` without indication, and the usual debugging steps - `$TERM`, `infocmp`, etc. did all report using `terminfo/a/alacritty` in that case. In neovim, I lost the ability to set title and render italics.
I'd rather keep searching here, and return the first (non-ENOENT, falling back to ENOENT) error  if the search didn't ultimately succeed. This would keep the error behavior but not stop early.

**Comment by justinmk** [comment]
@pschyska feel like sending a PR to explore that idea?

**Comment by pschyska** [comment]
Maybe, but no promises as I've never used C 🙂

**Pull request merged**
